[k8s_control]
k8master ansible_host=10.10.1.70

[k8s_workers]
worker1 ansible_host=10.10.2.71
worker2 ansible_host=10.10.3.72

[k8s_nodes:children]
k8s_control
k8s_workers

[k8s_nodes:vars]
ansible_user=k8
ansible_python_interpreter=/usr/bin/python3
